spring:
  datasource:
#    url: jdbc:mysql://110.40.206.206:3306/ib
#    username: IB
#    password: RRXY6tbAr5CY4rP6
    url: jdbc:mysql://49.235.179.94/ib
    username: ib
    password: AMEftwWK2cakz5Nh
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
#      host: 110.40.206.206
      host: 49.235.179.94
      port: 6379
      database: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8190

grpc:
  client:
    rag-service:
      address: static://127.0.0.1:50051
      negotiationType: plaintext
    agent-service:
      address: 'static://localhost:50052'
      enableKeepAlive: true
      negotiationType: plaintext